name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Congrats! you successfully created an issue in Sriansh's repo 🤭"
        pr-message: "Congrats! you made your first pull request in Sriansh's GitHub repository 🥳🥳"
